### ISSUE TITLE
Investigate if we need Flex Volume plugins as mentioned in the KEP

### ISSUE THREAD

**Issue by dims** [dims/openstack-cloud-controller-manager#24]
Do we?

**Comment by edisonxiang** [comment]
@dims, In my opinion, we should integrate with CSI plugin.
But now the external cloud controller manager have no progress on how to do that.
I found the only interface which is related with volume is ```GetLabelsForVolume```
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L213
So I think we can focus on the Node Controller and Service Controller for external OpenStack Cloud Controller Manager:)
