### ISSUE TITLE
Launch external openstack-cloud-controller-manager in devstack plugin.sh process

### ISSUE THREAD

**Issue by kiwik** [dims/openstack-cloud-controller-manager#75]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When we config devstack to enable plugin openstack-cloud-controller-manager, devstack process will launch kubernetes, but don't launch external openstack-cloud-controller-manager binary, and don't set the suitable cloud-config file, that cause we have to config something manually after devstack process end.

**What you expected to happen**:
When devstack process finish, kubernetes and external openstack-cloud-controller-manager are launched with correct configuration, those instances can talk with OpenStack that deployed by devstack.

**How to reproduce it (as minimally and precisely as possible)**:
1. enable_plugin openstack-cloud-controller-manager in devstack local.conf
2. run stack.sh

**Anything else we need to know?**:
N/A

**Environment**:
- openstack-cloud-controller-manager version:
```bash
$ git log -1
commit 391a2a0f79e08deb445a7a726b6c5ce85155db3e
Merge: 692c16e e77320e
Author: Davanum Srinivas <davanum@gmail.com>
Date:   Thu Feb 8 15:10:48 2018 -0500

    Merge pull request #74 from dims/add-support-for-csi

    Add support for csi
```

**Comment by dims** [comment]
@kiwik yep, we can use hack/local-up-cluster.sh to launch kubernetes. please see details in:
https://github.com/dims/openstack-cloud-controller-manager/issues/34#issuecomment-363903625

The other choice is to run kubeadm, but i think it's easier to deal with local-up-cluster.sh as kubeadm starts kubernetes processes inside pods/daemonsets which would be harder to deal with in a CI environment. Not ruling that out, just that we start with local-up-cluster.sh

**Comment by dims** [comment]
added some info in https://github.com/dims/openstack-cloud-controller-manager/issues/26 which will help
