### ISSUE TITLE
k8s-keystone-auth should support the new format keystone url

### ISSUE THREAD

**Issue by liu-sheng** [dims/openstack-cloud-controller-manager#88]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Now when we start k8s-keystone-auth with "--keystone-url  http://172.24.5.1/identity" specified, the k8s-keystone-auth process cannot be started, and raise following error:
Unable to find identity API v3 version : No supported version available from endpoint http://172.24.5.1/identity/

**What you expected to happen**:

k8s-keystone-auth can start with new format keystone url, like http://172.24.5.1/identity

**How to reproduce it (as minimally and precisely as possible)**:

Start k8s-keystone-auth with --keystone-url parameter specified.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
cc @Fedosin
